

################################################################################
## Form generated from reading UI file 'CharacterWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName('MainWindow')
        MainWindow.resize(800, 440)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred) #type: ignore
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFixedSize(800, 440)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        
        ## 基本信息
        # ID
        self.label_Text_ID = QLabel(self.centralwidget)
        self.label_Text_ID.setObjectName('label_Text_ID')
        self.label_Text_ID.setGeometry(QRect(190, 53, 31, 16))
        self.label_Text_ID.setText('ID')
        self.lineEdit_ID = QLineEdit(self.centralwidget)
        self.lineEdit_ID.setObjectName('lineEdit_ID')
        self.lineEdit_ID.setGeometry(QRect(220, 50, 101, 20))
        # 称号
        self.label_Text_Title = QLabel(self.centralwidget)
        self.label_Text_Title.setObjectName('label_Text_Title')
        self.label_Text_Title.setGeometry(QRect(190, 83, 31, 16))
        self.label_Text_Title.setText('称号')
        self.lineEdit_Title = QLineEdit(self.centralwidget)
        self.lineEdit_Title.setObjectName('lineEdit_Title')
        self.lineEdit_Title.setGeometry(QRect(220, 80, 131, 20))
        # 名称
        self.label_Text_Name = QLabel(self.centralwidget)
        self.label_Text_Name.setObjectName('label_Text_Name')
        self.label_Text_Name.setGeometry(QRect(190, 113, 31, 16))
        self.label_Text_Name.setText('名称')
        self.lineEdit_Name = QLineEdit(self.centralwidget)
        self.lineEdit_Name.setObjectName('lineEdit_Name')
        self.lineEdit_Name.setGeometry(QRect(220, 110, 131, 20))
        # 设计师      
        self.label_Text_Designer = QLabel(self.centralwidget)
        self.label_Text_Designer.setObjectName('label_Text_Designer')
        self.label_Text_Designer.setGeometry(QRect(190, 143, 31, 16))
        self.label_Text_Designer.setText('设计')
        self.lineEdit_Designer = QLineEdit(self.centralwidget)
        self.lineEdit_Designer.setObjectName('lineEdit_Designer')
        self.lineEdit_Designer.setGeometry(QRect(220, 140, 131, 20))
        # 设计状态
        self.checkBox_Finish = QCheckBox(self.centralwidget)
        self.checkBox_Finish.setObjectName('checkBox_Finish')
        self.checkBox_Finish.setGeometry(QRect(360, 140, 81, 20))
        self.checkBox_Finish.setText('已设计')
        # 性别
        self.label_Text_Sex = QLabel(self.centralwidget)
        self.label_Text_Sex.setObjectName('label_Text_Sex')
        self.label_Text_Sex.setGeometry(QRect(360, 83, 31, 16))
        self.label_Text_Sex.setText('性别')
        self.comboBox_Sex = QComboBox(self.centralwidget)
        self.comboBox_Sex.addItem('男')
        self.comboBox_Sex.addItem('女')
        self.comboBox_Sex.addItem('其他')
        self.comboBox_Sex.setObjectName('comboBox_Sex')
        self.comboBox_Sex.setGeometry(QRect(390, 80, 68, 22))
        # 星级
        self.label_Text_StarLevel = QLabel(self.centralwidget)
        self.label_Text_StarLevel.setObjectName('label_Text_StarLevel')
        self.label_Text_StarLevel.setGeometry(QRect(360, 113, 31, 16))
        self.label_Text_StarLevel.setText('星级')
        self.comboBox_StarLevel = QComboBox(self.centralwidget)
        self.comboBox_StarLevel.addItem('5')
        self.comboBox_StarLevel.addItem('4')
        self.comboBox_StarLevel.setObjectName('comboBox_StarLevel')
        self.comboBox_StarLevel.setGeometry(QRect(390, 110, 68, 22))
        # 所属
        self.label_Text_Country = QLabel(self.centralwidget)
        self.label_Text_Country.setObjectName('label_Text_Country')
        self.label_Text_Country.setGeometry(QRect(470, 83, 31, 16))
        self.label_Text_Country.setText('所属')
        self.comboBox_Country = QComboBox(self.centralwidget)
        self.comboBox_Country.addItem('蒙德')
        self.comboBox_Country.addItem('璃月')
        self.comboBox_Country.addItem('稻妻')
        self.comboBox_Country.addItem('须弥')
        self.comboBox_Country.addItem('枫丹')
        self.comboBox_Country.addItem('纳塔')
        self.comboBox_Country.addItem('至冬')
        self.comboBox_Country.addItem('坎瑞亚')
        self.comboBox_Country.addItem('其他')
        self.comboBox_Country.setObjectName('comboBox_Country')
        self.comboBox_Country.setGeometry(QRect(500, 80, 68, 22))
        # 元素
        self.label_Text_Element = QLabel(self.centralwidget)
        self.label_Text_Element.setObjectName('label_Text_Element')
        self.label_Text_Element.setGeometry(QRect(470, 113, 31, 16))
        self.label_Text_Element.setText('元素')
        self.comboBox_Element = QComboBox(self.centralwidget)
        self.comboBox_Element.addItem('火元素')
        self.comboBox_Element.addItem('水元素')
        self.comboBox_Element.addItem('风元素')
        self.comboBox_Element.addItem('雷元素')
        self.comboBox_Element.addItem('草元素')
        self.comboBox_Element.addItem('冰元素')
        self.comboBox_Element.addItem('岩元素')
        self.comboBox_Element.addItem('其他')
        self.comboBox_Element.setObjectName('comboBox_Element')
        self.comboBox_Element.setGeometry(QRect(500, 110, 68, 22))
        # 体力
        self.label_Text_Health = QLabel(self.centralwidget)
        self.label_Text_Health.setObjectName('label_Text_Health')
        self.label_Text_Health.setGeometry(QRect(330, 53, 31, 16))
        self.label_Text_Health.setText('体力')
        self.spinBox_HP = QSpinBox(self.centralwidget)
        self.spinBox_HP.setObjectName('spinBox_HP')
        self.spinBox_HP.setGeometry(QRect(360, 50, 42, 22))
        self.spinBox_HPMax = QSpinBox(self.centralwidget)
        self.spinBox_HPMax.setObjectName('spinBox_HPMax')
        self.spinBox_HPMax.setGeometry(QRect(420, 50, 42, 22))
        self.label_Text_Health_ = QLabel(self.centralwidget)
        self.label_Text_Health_.setObjectName('label_Text_Health_')
        self.label_Text_Health_.setGeometry(QRect(408, 53, 16, 16))
        self.label_Text_Health_.setText('/')
        # 初始护甲
        self.label_Text_Armor = QLabel(self.centralwidget)
        self.label_Text_Armor.setObjectName('label_Text_Armor')
        self.label_Text_Armor.setGeometry(QRect(470, 53, 51, 16))
        self.label_Text_Armor.setText('初始护甲')
        self.spinBox_Armor = QSpinBox(self.centralwidget)
        self.spinBox_Armor.setObjectName('spinBox_Armor')
        self.spinBox_Armor.setGeometry(QRect(530, 50, 42, 22))
        self.label_Text_AllName = QLabel(self.centralwidget)
        self.label_Text_AllName.setObjectName('label_Text_AllName')
        self.label_Text_AllName.setGeometry(QRect(190, 20, 381, 20))
        self.label_Text_AllName.setTextFormat(Qt.PlainText) #type: ignore
        self.label_Text_AllName.setWordWrap(False)
        self.label_Text_AllName.setOpenExternalLinks(False)
        
        ## 额外内容
        # 版本号
        self.label_Text_Verions = QLabel(self.centralwidget)
        self.label_Text_Verions.setObjectName('label_Text_Verions')
        self.label_Text_Verions.setGeometry(QRect(596, 380, 51, 16))
        self.label_Text_VerionsInfo = QLabel(self.centralwidget)
        self.label_Text_VerionsInfo.setObjectName('label_Text_VerionsInfo')
        self.label_Text_VerionsInfo.setGeometry(QRect(650, 380, 141, 16))
        # 分割线
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName('line')
        self.line.setGeometry(QRect(170, 20, 20, 371))
        self.line.setFrameShape(QFrame.VLine) #type: ignore
        self.line.setFrameShadow(QFrame.Sunken) #type: ignore
        # 图片框
        self.label_Image = QLabel(self.centralwidget)
        self.label_Image.setObjectName('label_Image')
        self.label_Image.setGeometry(QRect(590, 50, 200, 320))
        self.label_Image.setStyleSheet('border: 2px solid rgb(0,0,0)')
        self.label_Image.setFrameShape(QFrame.NoFrame) #type: ignore
        self.label_Image.setFrameShadow(QFrame.Plain) #type: ignore
        self.label_Image.setLineWidth(10)
        self.label_Image.setMidLineWidth(10)
        
        ## 功能区
        # 右上按钮处
        self.pushButton_ImageBuild = QPushButton(self.centralwidget)
        self.pushButton_ImageBuild.setObjectName('pushButton_ImageBuild')
        self.pushButton_ImageBuild.setGeometry(QRect(590, 20, 61, 24))
        self.pushButton_Save = QPushButton(self.centralwidget)
        self.pushButton_Save.setObjectName('pushButton_Save')
        self.pushButton_Save.setGeometry(QRect(660, 20, 61, 24))
        self.pushButton_Output = QPushButton(self.centralwidget)
        self.pushButton_Output.setObjectName('pushButton_Output')
        self.pushButton_Output.setGeometry(QRect(730, 20, 61, 24))
        # 新增技能
        self.pushButton_SkillAdd = QPushButton(self.centralwidget)
        self.pushButton_SkillAdd.setObjectName('pushButton_SkillAdd')
        self.pushButton_SkillAdd.setGeometry(QRect(510, 140, 61, 24))
        # 新增角色
        self.pushButton_NewCharacter = QPushButton(self.centralwidget)
        self.pushButton_NewCharacter.setObjectName('pushButton_NewCharacter')
        self.pushButton_NewCharacter.setGeometry(QRect(520, 20, 61, 24))
        # 左侧筛选框
        self.label_Text_FliterS = QLabel(self.centralwidget)
        self.label_Text_FliterS.setObjectName('label_Text_FliterS')
        self.label_Text_FliterS.setGeometry(QRect(20, 24, 71, 16))     
        self.label_Text_FliterS.setText('通过元素筛选')   
        self.comboBox_Filter = QComboBox(self.centralwidget)
        self.comboBox_Filter.addItem('全部')
        self.comboBox_Filter.addItem('火元素')
        self.comboBox_Filter.addItem('水元素')
        self.comboBox_Filter.addItem('风元素')
        self.comboBox_Filter.addItem('雷元素')
        self.comboBox_Filter.addItem('草元素')
        self.comboBox_Filter.addItem('冰元素')
        self.comboBox_Filter.addItem('岩元素')
        self.comboBox_Filter.addItem('其他')
        self.comboBox_Filter.setObjectName('comboBox_Filter')
        self.comboBox_Filter.setGeometry(QRect(100, 21, 68, 22))
        # 左侧显示处
        self.listWidget_List = QListWidget(self.centralwidget)
        self.listWidget_List.setObjectName('listWidget_List')
        self.listWidget_List.setGeometry(QRect(20, 50, 151, 311))
        
        # 左下查看方式
        self.label_Text_FilterN = QLabel(self.centralwidget)
        self.label_Text_FilterN.setObjectName('label_Text_FilterN')
        self.label_Text_FilterN.setGeometry(QRect(20, 370, 51, 16))
        self.label_Text_FilterN.setText('查看方式')
        self.radioButton_FliterName = QRadioButton(self.centralwidget)
        self.radioButton_FliterName.setObjectName('radioButton_FliterName')
        self.radioButton_FliterName.setGeometry(QRect(120, 368, 51, 20))
        self.radioButton_FliterName.setText('名称')
        self.radioButton_FliterID = QRadioButton(self.centralwidget)
        self.radioButton_FliterID.setObjectName('radioButton_FliterID')
        self.radioButton_FliterID.setGeometry(QRect(80, 368, 41, 20))
        self.radioButton_FliterID.setText('ID')
        
        # 技能区
        self.tabWidget_Skill = QTabWidget(self.centralwidget)
        self.tabWidget_Skill.setObjectName('tabWidget_Skill')
        self.tabWidget_Skill.setGeometry(QRect(190, 170, 391, 231))
        self.tab_Skill1 = QWidget()
        self.tab_Skill1.setObjectName('tab_Skill1')
        self.lineEdit_Skill1_Name = QLineEdit(self.tab_Skill1)
        self.lineEdit_Skill1_Name.setObjectName('lineEdit_Skill1_Name')
        self.lineEdit_Skill1_Name.setGeometry(QRect(70, 8, 113, 20))
        self.label_Text_Skill1_Name = QLabel(self.tab_Skill1)
        self.label_Text_Skill1_Name.setObjectName('label_Text_Skill1_Name')
        self.label_Text_Skill1_Name.setGeometry(QRect(10, 10, 51, 16))
        self.label_Text_Skill1_Description = QLabel(self.tab_Skill1)
        self.label_Text_Skill1_Description.setObjectName('label_Text_Skill1_Description')
        self.label_Text_Skill1_Description.setGeometry(QRect(10, 70, 51, 16))
        self.textEdit_Skill1_Description = QTextEdit(self.tab_Skill1)
        self.textEdit_Skill1_Description.setObjectName('textEdit_Skill1_Description')
        self.textEdit_Skill1_Description.setGeometry(QRect(70, 70, 301, 121))
        self.checkBox_Skill1_Enabled = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Enabled.setObjectName('checkBox_Skill1_Enabled')
        self.checkBox_Skill1_Enabled.setGeometry(QRect(300, 10, 51, 20))
        self.checkBox_Skill1_Enabled.setText('')
        self.checkBox_Skill1_Visibled = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Visibled.setObjectName('checkBox_Skill1_Visibled')
        self.checkBox_Skill1_Visibled.setGeometry(QRect(250, 10, 51, 20))
        self.tabWidget_Skill.addTab(self.tab_Skill1, '')
    #     self.tab_Skill2 = QWidget()
    #     self.tab_Skill2.setObjectName('tab_Skill2')
    #     self.lineEdit_Skill2_Name = QLineEdit(self.tab_Skill2)
    #     self.lineEdit_Skill2_Name.setObjectName('lineEdit_Skill2_Name')
    #     self.lineEdit_Skill2_Name.setGeometry(QRect(70, 8, 113, 20))
    #     self.label_Text_Skill2_Name = QLabel(self.tab_Skill2)
    #     self.label_Text_Skill2_Name.setObjectName('label_Text_Skill2_Name')
    #     self.label_Text_Skill2_Name.setGeometry(QRect(10, 10, 51, 16))
    #     self.label_Text_Skill2_Description = QLabel(self.tab_Skill2)
    #     self.label_Text_Skill2_Description.setObjectName('label_Text_Skill2_Description')
    #     self.label_Text_Skill2_Description.setGeometry(QRect(10, 70, 51, 16))
    #     self.textEdit_Skill2_Description = QTextEdit(self.tab_Skill2)
    #     self.textEdit_Skill2_Description.setObjectName('textEdit_Skill2_Description')
    #     self.textEdit_Skill2_Description.setGeometry(QRect(70, 70, 301, 121))
    #     self.checkBox_Skill2_Enabled = QCheckBox(self.tab_Skill2)
    #     self.checkBox_Skill2_Enabled.setObjectName('checkBox_Skill2_Enabled')
    #     self.checkBox_Skill2_Enabled.setGeometry(QRect(300, 10, 51, 20))
    #     self.checkBox_Skill2_Enabled.setText('')
    #     self.checkBox_Skill2_Visibled = QCheckBox(self.tab_Skill2)
    #     self.checkBox_Skill2_Visibled.setObjectName('checkBox_Skill2_Visibled')
    #     self.checkBox_Skill2_Visibled.setGeometry(QRect(250, 10, 51, 20))
    #     self.tabWidget_Skill.addTab(self.tab_Skill2, '')       
    #     self.tab_Skill3 = QWidget()
    #     self.tab_Skill3.setObjectName('tab_Skill3')
    #     self.lineEdit_Skill3_Name = QLineEdit(self.tab_Skill3)
    #     self.lineEdit_Skill3_Name.setObjectName('lineEdit_Skill3_Name')
    #     self.lineEdit_Skill3_Name.setGeometry(QRect(70, 8, 113, 20))
    #     self.label_Text_Skill3_Name = QLabel(self.tab_Skill3)
    #     self.label_Text_Skill3_Name.setObjectName('label_Text_Skill3_Name')
    #     self.label_Text_Skill3_Name.setGeometry(QRect(10, 10, 51, 16))
    #     self.label_Text_Skill3_Description = QLabel(self.tab_Skill3)
    #     self.label_Text_Skill3_Description.setObjectName('label_Text_Skill3_Description')
    #     self.label_Text_Skill3_Description.setGeometry(QRect(10, 70, 51, 16))
    #     self.textEdit_Skill3_Description = QTextEdit(self.tab_Skill3)
    #     self.textEdit_Skill3_Description.setObjectName('textEdit_Skill3_Description')
    #     self.textEdit_Skill3_Description.setGeometry(QRect(70, 70, 301, 121))
    #     self.checkBox_Skill3_Enabled = QCheckBox(self.tab_Skill3)
    #     self.checkBox_Skill3_Enabled.setObjectName('checkBox_Skill3_Enabled')
    #     self.checkBox_Skill3_Enabled.setGeometry(QRect(300, 10, 51, 20))
    #     self.checkBox_Skill3_Enabled.setText('')
    #     self.checkBox_Skill3_Visibled = QCheckBox(self.tab_Skill3)
    #     self.checkBox_Skill3_Visibled.setObjectName('checkBox_Skill3_Visibled')
    #     self.checkBox_Skill3_Visibled.setGeometry(QRect(250, 10, 51, 20))
    #     self.tabWidget_Skill.addTab(self.tab_Skill3, '')
    #     self.tab_Skill4 = QWidget()
    #     self.tab_Skill4.setObjectName('tab_Skill4')
    #     self.lineEdit_Skill4_Name = QLineEdit(self.tab_Skill4)
    #     self.lineEdit_Skill4_Name.setObjectName('lineEdit_Skill4_Name')
    #     self.lineEdit_Skill4_Name.setGeometry(QRect(70, 8, 113, 20))
    #     self.label_Text_Skill4_Name = QLabel(self.tab_Skill4)
    #     self.label_Text_Skill4_Name.setObjectName('label_Text_Skill4_Name')
    #     self.label_Text_Skill4_Name.setGeometry(QRect(10, 10, 51, 16))
    #     self.label_Text_Skill4_Description = QLabel(self.tab_Skill4)
    #     self.label_Text_Skill4_Description.setObjectName('label_Text_Skill4_Description')
    #     self.label_Text_Skill4_Description.setGeometry(QRect(10, 70, 51, 16))
    #     self.textEdit_Skill4_Description = QTextEdit(self.tab_Skill4)
    #     self.textEdit_Skill4_Description.setObjectName('textEdit_Skill4_Description')
    #     self.textEdit_Skill4_Description.setGeometry(QRect(70, 70, 301, 121))
    #     self.checkBox_Skill4_Enabled = QCheckBox(self.tab_Skill4)
    #     self.checkBox_Skill4_Enabled.setObjectName('checkBox_Skill4_Enabled')
    #     self.checkBox_Skill4_Enabled.setGeometry(QRect(300, 10, 51, 20))
    #     self.checkBox_Skill4_Enabled.setText('')
    #     self.checkBox_Skill4_Visibled = QCheckBox(self.tab_Skill4)
    #     self.checkBox_Skill4_Visibled.setObjectName('checkBox_Skill4_Visibled')
    #     self.checkBox_Skill4_Visibled.setGeometry(QRect(250, 10, 51, 20))
    #     self.tabWidget_Skill.addTab(self.tab_Skill4, '')
    #     self.tab_Skill5 = QWidget()
    #     self.tab_Skill5.setObjectName('tab_Skill5')
    #     self.lineEdit_Skill5_Name = QLineEdit(self.tab_Skill5)
    #     self.lineEdit_Skill5_Name.setObjectName('lineEdit_Skill5_Name')
    #     self.lineEdit_Skill5_Name.setGeometry(QRect(70, 8, 113, 20))
    #     self.label_Text_Skill5_Name = QLabel(self.tab_Skill5)
    #     self.label_Text_Skill5_Name.setObjectName('label_Text_Skill5_Name')
    #     self.label_Text_Skill5_Name.setGeometry(QRect(10, 10, 51, 16))
    #     self.label_Text_Skill5_Description = QLabel(self.tab_Skill5)
    #     self.label_Text_Skill5_Description.setObjectName('label_Text_Skill5_Description')
    #     self.label_Text_Skill5_Description.setGeometry(QRect(10, 70, 51, 16))
    #     self.textEdit_Skill5_Description = QTextEdit(self.tab_Skill5)
    #     self.textEdit_Skill5_Description.setObjectName('textEdit_Skill5_Description')
    #     self.textEdit_Skill5_Description.setGeometry(QRect(70, 70, 301, 121))
    #     self.checkBox_Skill5_Enabled = QCheckBox(self.tab_Skill5)
    #     self.checkBox_Skill5_Enabled.setObjectName('checkBox_Skill5_Enabled')
    #     self.checkBox_Skill5_Enabled.setGeometry(QRect(300, 10, 51, 20))
    #     self.checkBox_Skill5_Enabled.setText('')
    #     self.checkBox_Skill5_Visibled = QCheckBox(self.tab_Skill5)
    #     self.checkBox_Skill5_Visibled.setObjectName('checkBox_Skill5_Visibled')
    #     self.checkBox_Skill5_Visibled.setGeometry(QRect(250, 10, 51, 20))
    #     self.tabWidget_Skill.addTab(self.tab_Skill5, '')
    #     self.tab_Skill6 = QWidget()
    #     self.tab_Skill6.setObjectName('tab_Skill6')
    #     self.lineEdit_Skill6_Name = QLineEdit(self.tab_Skill6)
    #     self.lineEdit_Skill6_Name.setObjectName('lineEdit_Skill6_Name')
    #     self.lineEdit_Skill6_Name.setGeometry(QRect(70, 8, 113, 20))
    #     self.label_Text_Skill6_Name = QLabel(self.tab_Skill6)
    #     self.label_Text_Skill6_Name.setObjectName('label_Text_Skill6_Name')
    #     self.label_Text_Skill6_Name.setGeometry(QRect(10, 10, 51, 16))
    #     self.label_Text_Skill6_Description = QLabel(self.tab_Skill6)
    #     self.label_Text_Skill6_Description.setObjectName('label_Text_Skill6_Description')
    #     self.label_Text_Skill6_Description.setGeometry(QRect(10, 70, 51, 16))
    #     self.textEdit_Skill6_Description = QTextEdit(self.tab_Skill6)
    #     self.textEdit_Skill6_Description.setObjectName('textEdit_Skill6_Description')
    #     self.textEdit_Skill6_Description.setGeometry(QRect(70, 70, 301, 121))
    #     self.checkBox_Skill6_Enabled = QCheckBox(self.tab_Skill6)
    #     self.checkBox_Skill6_Enabled.setObjectName('checkBox_Skill6_Enabled')
    #     self.checkBox_Skill6_Enabled.setGeometry(QRect(300, 10, 51, 20))
    #     self.checkBox_Skill6_Enabled.setText('')
    #     self.checkBox_Skill6_Visibled = QCheckBox(self.tab_Skill6)
    #     self.checkBox_Skill6_Visibled.setObjectName('checkBox_Skill6_Visibled')
    #     self.checkBox_Skill6_Visibled.setGeometry(QRect(250, 10, 51, 20))
    #     self.tabWidget_Skill.addTab(self.tab_Skill6, '')
    #     self.tab_Skill7 = QWidget()
    #     self.tab_Skill7.setObjectName('tab_Skill7')
    #     self.lineEdit_Skill7_Name = QLineEdit(self.tab_Skill7)
    #     self.lineEdit_Skill7_Name.setObjectName('lineEdit_Skill7_Name')
    #     self.lineEdit_Skill7_Name.setGeometry(QRect(70, 8, 113, 20))
    #     self.label_Text_Skill7_Name = QLabel(self.tab_Skill7)
    #     self.label_Text_Skill7_Name.setObjectName('label_Text_Skill7_Name')
    #     self.label_Text_Skill7_Name.setGeometry(QRect(10, 10, 51, 16))
    #     self.label_Text_Skill7_Description = QLabel(self.tab_Skill7)
    #     self.label_Text_Skill7_Description.setObjectName('label_Text_Skill7_Description')
    #     self.label_Text_Skill7_Description.setGeometry(QRect(10, 70, 51, 16))
    #     self.textEdit_Skill7_Description = QTextEdit(self.tab_Skill7)
    #     self.textEdit_Skill7_Description.setObjectName('textEdit_Skill7_Description')
    #     self.textEdit_Skill7_Description.setGeometry(QRect(70, 70, 301, 121))
    #     self.checkBox_Skill7_Enabled = QCheckBox(self.tab_Skill7)
    #     self.checkBox_Skill7_Enabled.setObjectName('checkBox_Skill7_Enabled')
    #     self.checkBox_Skill7_Enabled.setGeometry(QRect(300, 10, 51, 20))
    #     self.checkBox_Skill7_Enabled.setText('')
    #     self.checkBox_Skill7_Visibled = QCheckBox(self.tab_Skill7)
    #     self.checkBox_Skill7_Visibled.setObjectName('checkBox_Skill7_Visibled')
    #     self.checkBox_Skill7_Visibled.setGeometry(QRect(250, 10, 51, 20))
    #     self.tabWidget_Skill.addTab(self.tab_Skill7, '')
    #     self.tab_Skill8 = QWidget()
    #     self.tab_Skill8.setObjectName('tab_Skill8')
    #     self.lineEdit_Skill8_Name = QLineEdit(self.tab_Skill8)
    #     self.lineEdit_Skill8_Name.setObjectName('lineEdit_Skill8_Name')
    #     self.lineEdit_Skill8_Name.setGeometry(QRect(70, 8, 113, 20))
    #     self.label_Text_Skill8_Name = QLabel(self.tab_Skill8)
    #     self.label_Text_Skill8_Name.setObjectName('label_Text_Skill8_Name')
    #     self.label_Text_Skill8_Name.setGeometry(QRect(10, 10, 51, 16))
    #     self.label_Text_Skill8_Description = QLabel(self.tab_Skill8)
    #     self.label_Text_Skill8_Description.setObjectName('label_Text_Skill8_Description')
    #     self.label_Text_Skill8_Description.setGeometry(QRect(10, 70, 51, 16))
    #     self.textEdit_Skill8_Description = QTextEdit(self.tab_Skill8)
    #     self.textEdit_Skill8_Description.setObjectName('textEdit_Skill8_Description')
    #     self.textEdit_Skill8_Description.setGeometry(QRect(70, 70, 301, 121))
    #     self.checkBox_Skill8_Enabled = QCheckBox(self.tab_Skill8)
    #     self.checkBox_Skill8_Enabled.setObjectName('checkBox_Skill8_Enabled')
    #     self.checkBox_Skill8_Enabled.setGeometry(QRect(300, 10, 51, 20))
    #     self.checkBox_Skill8_Enabled.setText('')
    #     self.checkBox_Skill8_Visibled = QCheckBox(self.tab_Skill8)
    #     self.checkBox_Skill8_Visibled.setObjectName('checkBox_Skill8_Visibled')
    #     self.checkBox_Skill8_Visibled.setGeometry(QRect(250, 10, 51, 20))
    #     self.tabWidget_Skill.addTab(self.tab_Skill8, '')
    # 
    #     self.tabWidget_Skill.setCurrentIndex(0)

        # 其他内容
        font = QFont()
        font.setBold(True)
        self.label_Text_AllName.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName('menubar')
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)
        QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setWindowTitle('GK-23a 设计师编辑器') #type: ignore

    # retranslateUi

