

################################################################################
## Form generated from reading UI file 'CharacterWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 440)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFixedSize(800, 440)
        # 技能区
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget_Skill = QTabWidget(self.centralwidget)
        self.tabWidget_Skill.setObjectName(u"tabWidget_Skill")
        self.tabWidget_Skill.setGeometry(QRect(190, 170, 391, 231))
        self.tab_Skill1 = QWidget()
        self.tab_Skill1.setObjectName(u"tab_Skill1")
        self.lineEdit_Skill1_Name = QLineEdit(self.tab_Skill1)
        self.lineEdit_Skill1_Name.setObjectName(u"lineEdit_Skill1_Name")
        self.lineEdit_Skill1_Name.setGeometry(QRect(70, 8, 113, 20))
        self.label_Text_Skill1_Name = QLabel(self.tab_Skill1)
        self.label_Text_Skill1_Name.setObjectName(u"label_Text_Skill1_Name")
        self.label_Text_Skill1_Name.setGeometry(QRect(10, 10, 51, 16))
        self.label_Text_Skill1_Type = QLabel(self.tab_Skill1)
        self.label_Text_Skill1_Type.setObjectName(u"label_Text_Skill1_Type")
        self.label_Text_Skill1_Type.setGeometry(QRect(10, 40, 51, 16))
        self.label_Text_Skill1_Description = QLabel(self.tab_Skill1)
        self.label_Text_Skill1_Description.setObjectName(u"label_Text_Skill1_Description")
        self.label_Text_Skill1_Description.setGeometry(QRect(10, 70, 51, 16))
        self.textEdit_Skill1_Description = QTextEdit(self.tab_Skill1)
        self.textEdit_Skill1_Description.setObjectName(u"textEdit_Skill1_Description")
        self.textEdit_Skill1_Description.setGeometry(QRect(70, 70, 301, 121))
        self.checkBox_Skill1_Shiming = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Shiming.setObjectName(u"checkBox_Skill1_Shiming")
        self.checkBox_Skill1_Shiming.setGeometry(QRect(310, 40, 61, 20))
        self.checkBox_Skill1_Xianding = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Xianding.setObjectName(u"checkBox_Skill1_Xianding")
        self.checkBox_Skill1_Xianding.setGeometry(QRect(130, 40, 61, 20))
        self.checkBox_Skill1_Suoding = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Suoding.setObjectName(u"checkBox_Skill1_Suoding")
        self.checkBox_Skill1_Suoding.setGeometry(QRect(70, 40, 61, 20))
        self.checkBox_Skill1_Juexing = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Juexing.setObjectName(u"checkBox_Skill1_Juexing")
        self.checkBox_Skill1_Juexing.setGeometry(QRect(250, 40, 61, 20))
        self.checkBox_Skill1_Zhuanhuan = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Zhuanhuan.setObjectName(u"checkBox_Skill1_Zhuanhuan")
        self.checkBox_Skill1_Zhuanhuan.setGeometry(QRect(190, 40, 61, 20))
        self.pushButton_Skill1_Delete = QPushButton(self.tab_Skill1)
        self.pushButton_Skill1_Delete.setObjectName(u"pushButton_Skill1_Delete")
        self.pushButton_Skill1_Delete.setGeometry(QRect(304, 8, 61, 24))
        self.checkBox_Skill1_Enable = QCheckBox(self.tab_Skill1)
        self.checkBox_Skill1_Enable.setObjectName(u"checkBox_Skill1_Enable")
        self.checkBox_Skill1_Enable.setGeometry(QRect(250, 10, 51, 20))
        self.tabWidget_Skill.addTab(self.tab_Skill1, "")
        self.tab_Skill2 = QWidget()
        self.tab_Skill2.setObjectName(u"tab_Skill2")
        self.label_Text_Skill2_Description = QLabel(self.tab_Skill2)
        self.label_Text_Skill2_Description.setObjectName(u"label_Text_Skill2_Description")
        self.label_Text_Skill2_Description.setGeometry(QRect(10, 70, 51, 16))
        self.label_Text_Skill2_Type = QLabel(self.tab_Skill2)
        self.label_Text_Skill2_Type.setObjectName(u"label_Text_Skill2_Type")
        self.label_Text_Skill2_Type.setGeometry(QRect(10, 40, 51, 16))
        self.label_Text_Skill2_Name = QLabel(self.tab_Skill2)
        self.label_Text_Skill2_Name.setObjectName(u"label_Text_Skill2_Name")
        self.label_Text_Skill2_Name.setGeometry(QRect(10, 10, 51, 16))
        self.textEdit_Skill2_Description = QTextEdit(self.tab_Skill2)
        self.textEdit_Skill2_Description.setObjectName(u"textEdit_Skill2_Description")
        self.textEdit_Skill2_Description.setGeometry(QRect(70, 70, 301, 121))
        self.lineEdit_Skill2_Name = QLineEdit(self.tab_Skill2)
        self.lineEdit_Skill2_Name.setObjectName(u"lineEdit_Skill2_Name")
        self.lineEdit_Skill2_Name.setGeometry(QRect(70, 8, 113, 20))
        self.checkBox_Skill2_Suoding = QCheckBox(self.tab_Skill2)
        self.checkBox_Skill2_Suoding.setObjectName(u"checkBox_Skill2_Suoding")
        self.checkBox_Skill2_Suoding.setGeometry(QRect(70, 40, 61, 20))
        self.checkBox_Skill2_Xianding = QCheckBox(self.tab_Skill2)
        self.checkBox_Skill2_Xianding.setObjectName(u"checkBox_Skill2_Xianding")
        self.checkBox_Skill2_Xianding.setGeometry(QRect(130, 40, 61, 20))
        self.checkBox_Skill2_Zhuanhuan = QCheckBox(self.tab_Skill2)
        self.checkBox_Skill2_Zhuanhuan.setObjectName(u"checkBox_Skill2_Zhuanhuan")
        self.checkBox_Skill2_Zhuanhuan.setGeometry(QRect(190, 40, 61, 20))
        self.checkBox_Skill2_Juexing = QCheckBox(self.tab_Skill2)
        self.checkBox_Skill2_Juexing.setObjectName(u"checkBox_Skill2_Juexing")
        self.checkBox_Skill2_Juexing.setGeometry(QRect(250, 40, 61, 20))
        self.checkBox_Skill2_Shiming = QCheckBox(self.tab_Skill2)
        self.checkBox_Skill2_Shiming.setObjectName(u"checkBox_Skill2_Shiming")
        self.checkBox_Skill2_Shiming.setGeometry(QRect(310, 40, 61, 20))
        self.pushButton_Skill2_Delete = QPushButton(self.tab_Skill2)
        self.pushButton_Skill2_Delete.setObjectName(u"pushButton_Skill2_Delete")
        self.pushButton_Skill2_Delete.setGeometry(QRect(304, 8, 61, 24))
        self.checkBox_Skill2_Enable = QCheckBox(self.tab_Skill2)
        self.checkBox_Skill2_Enable.setObjectName(u"checkBox_Skill2_Enable")
        self.checkBox_Skill2_Enable.setGeometry(QRect(250, 10, 51, 20))
        self.tabWidget_Skill.addTab(self.tab_Skill2, "")
        self.tab_Skill3 = QWidget()
        self.tab_Skill3.setObjectName(u"tab_Skill3")
        self.label_Text_Skill3_Description = QLabel(self.tab_Skill3)
        self.label_Text_Skill3_Description.setObjectName(u"label_Text_Skill3_Description")
        self.label_Text_Skill3_Description.setGeometry(QRect(10, 70, 51, 16))
        self.label_Text_Skill3_Type = QLabel(self.tab_Skill3)
        self.label_Text_Skill3_Type.setObjectName(u"label_Text_Skill3_Type")
        self.label_Text_Skill3_Type.setGeometry(QRect(10, 40, 51, 16))
        self.label_Text_Skill3_Name = QLabel(self.tab_Skill3)
        self.label_Text_Skill3_Name.setObjectName(u"label_Text_Skill3_Name")
        self.label_Text_Skill3_Name.setGeometry(QRect(10, 10, 51, 16))
        self.textEdit_Skill3_Description = QTextEdit(self.tab_Skill3)
        self.textEdit_Skill3_Description.setObjectName(u"textEdit_Skill3_Description")
        self.textEdit_Skill3_Description.setGeometry(QRect(70, 70, 301, 121))
        self.lineEdit_Skill3_Name = QLineEdit(self.tab_Skill3)
        self.lineEdit_Skill3_Name.setObjectName(u"lineEdit_Skill3_Name")
        self.lineEdit_Skill3_Name.setGeometry(QRect(70, 8, 113, 20))
        self.checkBox_Skill3_Suoding = QCheckBox(self.tab_Skill3)
        self.checkBox_Skill3_Suoding.setObjectName(u"checkBox_Skill3_Suoding")
        self.checkBox_Skill3_Suoding.setGeometry(QRect(70, 40, 61, 20))
        self.checkBox_Skill3_Xianding = QCheckBox(self.tab_Skill3)
        self.checkBox_Skill3_Xianding.setObjectName(u"checkBox_Skill3_Xianding")
        self.checkBox_Skill3_Xianding.setGeometry(QRect(130, 40, 61, 20))
        self.checkBox_Skill3_Zhuanhuan = QCheckBox(self.tab_Skill3)
        self.checkBox_Skill3_Zhuanhuan.setObjectName(u"checkBox_Skill3_Zhuanhuan")
        self.checkBox_Skill3_Zhuanhuan.setGeometry(QRect(190, 40, 61, 20))
        self.checkBox_Skill3_Juexing = QCheckBox(self.tab_Skill3)
        self.checkBox_Skill3_Juexing.setObjectName(u"checkBox_Skill3_Juexing")
        self.checkBox_Skill3_Juexing.setGeometry(QRect(250, 40, 61, 20))
        self.checkBox_Skill3_Shiming = QCheckBox(self.tab_Skill3)
        self.checkBox_Skill3_Shiming.setObjectName(u"checkBox_Skill3_Shiming")
        self.checkBox_Skill3_Shiming.setGeometry(QRect(310, 40, 61, 20))
        self.pushButton_Skill3_Delete = QPushButton(self.tab_Skill3)
        self.pushButton_Skill3_Delete.setObjectName(u"pushButton_Skill3_Delete")
        self.pushButton_Skill3_Delete.setGeometry(QRect(304, 8, 61, 24))
        self.checkBox_Skill3_Enable = QCheckBox(self.tab_Skill3)
        self.checkBox_Skill3_Enable.setObjectName(u"checkBox_Skill3_Enable")
        self.checkBox_Skill3_Enable.setGeometry(QRect(250, 10, 51, 20))
        self.tabWidget_Skill.addTab(self.tab_Skill3, "")
        self.label_Image = QLabel(self.centralwidget)
        self.label_Image.setObjectName(u"label_Image")
        self.label_Image.setGeometry(QRect(590, 50, 200, 320))
        self.label_Image.setStyleSheet(u"border: 2px solid rgb(0,0,0)")
        self.label_Image.setFrameShape(QFrame.NoFrame)
        self.label_Image.setFrameShadow(QFrame.Plain)
        self.label_Image.setLineWidth(10)
        self.label_Image.setMidLineWidth(10)
        self.label_Text_Name = QLabel(self.centralwidget)
        self.label_Text_Name.setObjectName(u"label_Text_Name")
        self.label_Text_Name.setGeometry(QRect(190, 113, 31, 16))
        self.label_Text_Title = QLabel(self.centralwidget)
        self.label_Text_Title.setObjectName(u"label_Text_Title")
        self.label_Text_Title.setGeometry(QRect(190, 83, 31, 16))
        self.lineEdit_ID = QLineEdit(self.centralwidget)
        self.lineEdit_ID.setObjectName(u"lineEdit_ID")
        self.lineEdit_ID.setGeometry(QRect(220, 50, 101, 20))
        self.lineEdit_Title = QLineEdit(self.centralwidget)
        self.lineEdit_Title.setObjectName(u"lineEdit_Title")
        self.lineEdit_Title.setGeometry(QRect(220, 80, 131, 20))
        self.lineEdit_Name = QLineEdit(self.centralwidget)
        self.lineEdit_Name.setObjectName(u"lineEdit_Name")
        self.lineEdit_Name.setGeometry(QRect(220, 110, 131, 20))
        self.lineEdit_Designer = QLineEdit(self.centralwidget)
        self.lineEdit_Designer.setObjectName(u"lineEdit_Designer")
        self.lineEdit_Designer.setGeometry(QRect(220, 140, 131, 20))
        self.label_Text_Designer = QLabel(self.centralwidget)
        self.label_Text_Designer.setObjectName(u"label_Text_Designer")
        self.label_Text_Designer.setGeometry(QRect(190, 143, 31, 16))
        self.label_Text_Sex = QLabel(self.centralwidget)
        self.label_Text_Sex.setObjectName(u"label_Text_Sex")
        self.label_Text_Sex.setGeometry(QRect(360, 83, 31, 16))
        self.label_Text_StarLevel = QLabel(self.centralwidget)
        self.label_Text_StarLevel.setObjectName(u"label_Text_StarLevel")
        self.label_Text_StarLevel.setGeometry(QRect(360, 113, 31, 16))
        self.label_Text_Element = QLabel(self.centralwidget)
        self.label_Text_Element.setObjectName(u"label_Text_Element")
        self.label_Text_Element.setGeometry(QRect(470, 113, 31, 16))
        self.label_Text_Country = QLabel(self.centralwidget)
        self.label_Text_Country.setObjectName(u"label_Text_Country")
        self.label_Text_Country.setGeometry(QRect(470, 83, 31, 16))
        self.pushButton_ImageBuild = QPushButton(self.centralwidget)
        self.pushButton_ImageBuild.setObjectName(u"pushButton_ImageBuild")
        self.pushButton_ImageBuild.setGeometry(QRect(590, 20, 61, 24))
        self.pushButton_Save = QPushButton(self.centralwidget)
        self.pushButton_Save.setObjectName(u"pushButton_Save")
        self.pushButton_Save.setGeometry(QRect(660, 20, 61, 24))
        self.comboBox_Sex = QComboBox(self.centralwidget)
        self.comboBox_Sex.addItem("")
        self.comboBox_Sex.addItem("")
        self.comboBox_Sex.addItem("")
        self.comboBox_Sex.setObjectName(u"comboBox_Sex")
        self.comboBox_Sex.setGeometry(QRect(390, 80, 68, 22))
        self.comboBox_StarLevel = QComboBox(self.centralwidget)
        self.comboBox_StarLevel.addItem("")
        self.comboBox_StarLevel.addItem("")
        self.comboBox_StarLevel.setObjectName(u"comboBox_StarLevel")
        self.comboBox_StarLevel.setGeometry(QRect(390, 110, 68, 22))
        self.comboBox_Element = QComboBox(self.centralwidget)
        self.comboBox_Element.addItem("")
        self.comboBox_Element.addItem("")
        self.comboBox_Element.addItem("")
        self.comboBox_Element.addItem("")
        self.comboBox_Element.addItem("")
        self.comboBox_Element.addItem("")
        self.comboBox_Element.addItem("")
        self.comboBox_Element.addItem("")
        self.comboBox_Element.setObjectName(u"comboBox_Element")
        self.comboBox_Element.setGeometry(QRect(500, 110, 68, 22))
        self.comboBox_Country = QComboBox(self.centralwidget)
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.addItem("")
        self.comboBox_Country.setObjectName(u"comboBox_Country")
        self.comboBox_Country.setGeometry(QRect(500, 80, 68, 22))
        self.listWidget_List = QListWidget(self.centralwidget)
        self.listWidget_List.setObjectName(u"listWidget_List")
        self.listWidget_List.setGeometry(QRect(20, 50, 151, 311))
        self.comboBox_Filter = QComboBox(self.centralwidget)
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.addItem("")
        self.comboBox_Filter.setObjectName(u"comboBox_Filter")
        self.comboBox_Filter.setGeometry(QRect(100, 21, 68, 22))
        self.label_Text_Fliter = QLabel(self.centralwidget)
        self.label_Text_Fliter.setObjectName(u"label_Text_Fliter")
        self.label_Text_Fliter.setGeometry(QRect(20, 24, 71, 16))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(170, 20, 20, 371))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_Text_ID = QLabel(self.centralwidget)
        self.label_Text_ID.setObjectName(u"label_Text_ID")
        self.label_Text_ID.setGeometry(QRect(190, 53, 31, 16))
        self.radioButton_FliterName = QRadioButton(self.centralwidget)
        self.radioButton_FliterName.setObjectName(u"radioButton_FliterName")
        self.radioButton_FliterName.setGeometry(QRect(120, 368, 51, 20))
        self.radioButton_FliterID = QRadioButton(self.centralwidget)
        self.radioButton_FliterID.setObjectName(u"radioButton_FliterID")
        self.radioButton_FliterID.setGeometry(QRect(80, 368, 41, 20))
        self.label_Text_Filter = QLabel(self.centralwidget)
        self.label_Text_Filter.setObjectName(u"label_Text_Filter")
        self.label_Text_Filter.setGeometry(QRect(20, 370, 51, 16))
        self.pushButton_Output = QPushButton(self.centralwidget)
        self.pushButton_Output.setObjectName(u"pushButton_Output")
        self.pushButton_Output.setGeometry(QRect(730, 20, 61, 24))
        self.label_Text_Verions = QLabel(self.centralwidget)
        self.label_Text_Verions.setObjectName(u"label_Text_Verions")
        self.label_Text_Verions.setGeometry(QRect(596, 380, 51, 16))
        self.label_Text_VerionsInfo = QLabel(self.centralwidget)
        self.label_Text_VerionsInfo.setObjectName(u"label_Text_VerionsInfo")
        self.label_Text_VerionsInfo.setGeometry(QRect(650, 380, 141, 16))
        self.checkBox_Finish = QCheckBox(self.centralwidget)
        self.checkBox_Finish.setObjectName(u"checkBox_Finish")
        self.checkBox_Finish.setGeometry(QRect(360, 140, 81, 20))
        self.pushButton_SkillAdd = QPushButton(self.centralwidget)
        self.pushButton_SkillAdd.setObjectName(u"pushButton_SkillAdd")
        self.pushButton_SkillAdd.setGeometry(QRect(510, 140, 61, 24))
        self.label_Text_Health = QLabel(self.centralwidget)
        self.label_Text_Health.setObjectName(u"label_Text_Health")
        self.label_Text_Health.setGeometry(QRect(330, 53, 31, 16))
        self.spinBox_HP = QSpinBox(self.centralwidget)
        self.spinBox_HP.setObjectName(u"spinBox_HP")
        self.spinBox_HP.setGeometry(QRect(360, 50, 42, 22))
        self.spinBox_HPMax = QSpinBox(self.centralwidget)
        self.spinBox_HPMax.setObjectName(u"spinBox_HPMax")
        self.spinBox_HPMax.setGeometry(QRect(420, 50, 42, 22))
        self.label_Text_Health_ = QLabel(self.centralwidget)
        self.label_Text_Health_.setObjectName(u"label_Text_Health_")
        self.label_Text_Health_.setGeometry(QRect(408, 53, 16, 16))
        self.label_Text_Armor = QLabel(self.centralwidget)
        self.label_Text_Armor.setObjectName(u"label_Text_Armor")
        self.label_Text_Armor.setGeometry(QRect(470, 53, 51, 16))
        self.spinBox_Armor = QSpinBox(self.centralwidget)
        self.spinBox_Armor.setObjectName(u"spinBox_Armor")
        self.spinBox_Armor.setGeometry(QRect(530, 50, 42, 22))
        self.label_Text_AllName = QLabel(self.centralwidget)
        self.label_Text_AllName.setObjectName(u"label_Text_AllName")
        self.label_Text_AllName.setGeometry(QRect(190, 20, 381, 20))
        self.label_Text_AllName.setTextFormat(Qt.PlainText)
        self.label_Text_AllName.setWordWrap(False)
        self.label_Text_AllName.setOpenExternalLinks(False)
        self.pushButton_NewCharacter = QPushButton(self.centralwidget)
        self.pushButton_NewCharacter.setObjectName(u"pushButton_NewCharacter")
        self.pushButton_NewCharacter.setGeometry(QRect(520, 20, 61, 24))
        font = QFont()
        font.setBold(True)
        self.label_Text_AllName.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget_Skill.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GK-23a \u8bbe\u8ba1\u5e08\u7f16\u8f91\u5668", None))
        self.label_Text_Skill1_Name.setText(QCoreApplication.translate("MainWindow", u"\u6280\u80fd\u540d\u79f0", None))
        self.label_Text_Skill1_Type.setText(QCoreApplication.translate("MainWindow", u"\u6280\u80fd\u7c7b\u578b", None))
        self.label_Text_Skill1_Description.setText(QCoreApplication.translate("MainWindow", u"\u6280\u80fd\u63cf\u8ff0", None))
        self.checkBox_Skill1_Shiming.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u547d\u6280", None))
        self.checkBox_Skill1_Xianding.setText(QCoreApplication.translate("MainWindow", u"\u9650\u5b9a\u6280", None))
        self.checkBox_Skill1_Suoding.setText(QCoreApplication.translate("MainWindow", u"\u9501\u5b9a\u6280", None))
        self.checkBox_Skill1_Juexing.setText(QCoreApplication.translate("MainWindow", u"\u89c9\u9192\u6280", None))
        self.checkBox_Skill1_Zhuanhuan.setText(QCoreApplication.translate("MainWindow", u"\u8f6c\u6362\u6280", None))
        self.pushButton_Skill1_Delete.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u6280\u80fd", None))
        self.checkBox_Skill1_Enable.setText(QCoreApplication.translate("MainWindow", u"\u53ef\u89c1", None))
        # 技能区
        self.tabWidget_Skill.setTabText(self.tabWidget_Skill.indexOf(self.tab_Skill1), QCoreApplication.translate("MainWindow", u"\u6280\u80fd1", None))
        self.label_Text_Skill2_Description.setText(QCoreApplication.translate("MainWindow", u"\u6280\u80fd\u63cf\u8ff0", None))
        self.label_Text_Skill2_Type.setText(QCoreApplication.translate("MainWindow", u"\u6280\u80fd\u7c7b\u578b", None))
        self.label_Text_Skill2_Name.setText(QCoreApplication.translate("MainWindow", u"\u6280\u80fd\u540d\u79f0", None))
        self.checkBox_Skill2_Suoding.setText(QCoreApplication.translate("MainWindow", u"\u9501\u5b9a\u6280", None))
        self.checkBox_Skill2_Xianding.setText(QCoreApplication.translate("MainWindow", u"\u9650\u5b9a\u6280", None))
        self.checkBox_Skill2_Zhuanhuan.setText(QCoreApplication.translate("MainWindow", u"\u8f6c\u6362\u6280", None))
        self.checkBox_Skill2_Juexing.setText(QCoreApplication.translate("MainWindow", u"\u89c9\u9192\u6280", None))
        self.checkBox_Skill2_Shiming.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u547d\u6280", None))
        self.pushButton_Skill2_Delete.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u6280\u80fd", None))
        self.checkBox_Skill2_Enable.setText(QCoreApplication.translate("MainWindow", u"\u53ef\u89c1", None))
        self.tabWidget_Skill.setTabText(self.tabWidget_Skill.indexOf(self.tab_Skill2), QCoreApplication.translate("MainWindow", u"\u6280\u80fd2", None))
        self.label_Image.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247", None))
        self.label_Text_Name.setText(QCoreApplication.translate("MainWindow", u"\u540d\u79f0", None))
        self.label_Text_Title.setText(QCoreApplication.translate("MainWindow", u"\u79f0\u53f7", None))
        self.label_Text_Designer.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u8ba1", None))
        self.label_Text_Sex.setText(QCoreApplication.translate("MainWindow", u"\u6027\u522b", None))
        self.label_Text_StarLevel.setText(QCoreApplication.translate("MainWindow", u"\u661f\u7ea7", None))
        self.label_Text_Element.setText(QCoreApplication.translate("MainWindow", u"\u5143\u7d20", None))
        self.label_Text_Country.setText(QCoreApplication.translate("MainWindow", u"\u6240\u5c5e", None))
        self.pushButton_ImageBuild.setText(QCoreApplication.translate("MainWindow", u"\u751f\u6210\u56fe\u7247", None))
        self.pushButton_Save.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.comboBox_Sex.setItemText(0, QCoreApplication.translate("MainWindow", "男", None))
        self.comboBox_Sex.setItemText(1, QCoreApplication.translate("MainWindow", "女", None))
        self.comboBox_Sex.setItemText(2, QCoreApplication.translate("MainWindow", "其他", None))

        self.comboBox_StarLevel.setItemText(0, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_StarLevel.setItemText(1, QCoreApplication.translate("MainWindow", u"4", None))

        self.comboBox_Element.setItemText(0, QCoreApplication.translate("MainWindow", u"\u706b\u5143\u7d20", None))
        self.comboBox_Element.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6c34\u5143\u7d20", None))
        self.comboBox_Element.setItemText(2, QCoreApplication.translate("MainWindow", u"\u98ce\u5143\u7d20", None))
        self.comboBox_Element.setItemText(3, QCoreApplication.translate("MainWindow", u"\u96f7\u5143\u7d20", None))
        self.comboBox_Element.setItemText(4, QCoreApplication.translate("MainWindow", u"\u8349\u5143\u7d20", None))
        self.comboBox_Element.setItemText(5, QCoreApplication.translate("MainWindow", u"\u51b0\u5143\u7d20", None))
        self.comboBox_Element.setItemText(6, QCoreApplication.translate("MainWindow", u"\u5ca9\u5143\u7d20", None))
        self.comboBox_Element.setItemText(7, QCoreApplication.translate("MainWindow", u"\u5176\u4ed6", None))

        self.comboBox_Country.setItemText(0, QCoreApplication.translate("MainWindow", u"\u8499\u5fb7", None))
        self.comboBox_Country.setItemText(1, QCoreApplication.translate("MainWindow", u"\u7483\u6708", None))
        self.comboBox_Country.setItemText(2, QCoreApplication.translate("MainWindow", u"\u7a3b\u59bb", None))
        self.comboBox_Country.setItemText(3, QCoreApplication.translate("MainWindow", u"\u987b\u5f25", None))
        self.comboBox_Country.setItemText(4, QCoreApplication.translate("MainWindow", u"\u67ab\u4e39", None))
        self.comboBox_Country.setItemText(5, QCoreApplication.translate("MainWindow", u"\u7eb3\u5854", None))
        self.comboBox_Country.setItemText(6, QCoreApplication.translate("MainWindow", u"\u81f3\u51ac", None))
        self.comboBox_Country.setItemText(7, QCoreApplication.translate("MainWindow", u"\u574e\u745e\u4e9a", None))
        self.comboBox_Country.setItemText(8, QCoreApplication.translate("MainWindow", u"\u5176\u4ed6", None))

        self.comboBox_Filter.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5168\u90e8", None))
        self.comboBox_Filter.setItemText(1, QCoreApplication.translate("MainWindow", u"\u706b\u5143\u7d20", None))
        self.comboBox_Filter.setItemText(2, QCoreApplication.translate("MainWindow", u"\u6c34\u5143\u7d20", None))
        self.comboBox_Filter.setItemText(3, QCoreApplication.translate("MainWindow", u"\u98ce\u5143\u7d20", None))
        self.comboBox_Filter.setItemText(4, QCoreApplication.translate("MainWindow", u"\u96f7\u5143\u7d20", None))
        self.comboBox_Filter.setItemText(5, QCoreApplication.translate("MainWindow", u"\u8349\u5143\u7d20", None))
        self.comboBox_Filter.setItemText(6, QCoreApplication.translate("MainWindow", u"\u51b0\u5143\u7d20", None))
        self.comboBox_Filter.setItemText(7, QCoreApplication.translate("MainWindow", u"\u5ca9\u5143\u7d20", None))
        self.comboBox_Filter.setItemText(8, QCoreApplication.translate("MainWindow", u"\u5176\u4ed6", None))

        self.label_Text_Fliter.setText(QCoreApplication.translate("MainWindow", u"\u901a\u8fc7\u5143\u7d20\u7b5b\u9009", None))
        self.label_Text_ID.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.radioButton_FliterName.setText(QCoreApplication.translate("MainWindow", u"\u540d\u79f0", None))
        self.radioButton_FliterID.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_Text_Filter.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u65b9\u5f0f", None))
        self.pushButton_Output.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
        self.label_Text_Verions.setText(QCoreApplication.translate("MainWindow", u"Verions.", None))
        self.label_Text_VerionsInfo.setText(QCoreApplication.translate("MainWindow", u"Beta-0318", None))
        self.checkBox_Finish.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u8ba1\u5df2\u5b8c\u6210", None))
        self.pushButton_SkillAdd.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e\u6280\u80fd", None))
        self.label_Text_Health.setText(QCoreApplication.translate("MainWindow", u"\u4f53\u529b", None))
        self.label_Text_Health_.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.label_Text_Armor.setText(QCoreApplication.translate("MainWindow", u"\u521d\u59cb\u62a4\u7532", None))
        self.pushButton_NewCharacter.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u89d2\u8272", None))
    # retranslateUi

